name: 'Federal Physical Access Control System Guide'
description: 'PACS guidance for Federal agencies on analyzing risk and procuring solutions'
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - pacs
    - physical
    - access
contact:
    email: icam@gsa.gov
