# Site settings

title: Physical Access Control System Guide
name: Physical Access Control System Guide
email: icam@gsa.gov
author:
    name: FICAM
description: Information on the US Federal Physical Access Control Systems (PACS)
highlighter: rouge
repo_url: https://github.com/GSA/ficam-pacs
baseurl: '/ficam-pacs'
branch: federalist-pages
# Federalist overwrites the site.branch value when deploying
# the site.branch was used in dynamic link generation for objects like Edit Page
# we want the dynamic links to send users to the staging branch.  Adding new site variable to ensure federalist doesn't overwrite.
editbranch: staging


# Links
# List links that you would like to appear on the top navigation bar here
navbar:
- title: idmanagement.gov
  description: idmanagement.gov
  url: https://www.idmanagement.gov
- title: Federal ICAM Architecture
  description: Federal ICAM Architecture
  url: https://arch.idmanagement.gov
- title: PIV Guides
  description: PIV Guides
  url: https://piv.idmanagement.gov
- title: Federal PKI Guides
  description: Federal PKI Guides
  url: https://fpki.idmanagement.gov
#- title: Federal ICAM PACS Guides
#  description: Federal ICAM PACS Guides
#  url: https://github.com/gsa/ficam-pacs

# Build settings
markdown: kramdown

#kramdown:
#  input: GFM
# syntax_highlighter: rouge

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Introduction
  url: ''
  internal: true
  coll: false
- text: Types of Physical Access <br>Control Systems
  url: pacs/
  internal: true
  coll: false
- text: Aligning Facility Security Level and Authentication
  url: alignfslandauth/
  internal: true
  coll: false
- text: Procurements
  url: procure/
  internal: true
  coll: false
- text: Training
  url: train/
  internal: true
  coll: false
- text: Lessons Learned
  url: lessonslearned/
  internal: true
  coll: false
- text: Standards, Policies, and Guidance
  url: standards/
  internal: true
  coll: false 
- text: Glossary
  url: glossary/
  internal: true
  coll: false 
- text: Contribute
  url: contribute/
  internal: true
  coll: false

#https://github.com/jekyll/jekyll/issues/2346
#collections:
#  faq:
#   label: "FAQ"
#   permalink: /faq/:path/
#   output: true



include:
- _stylesheets
- _javascript

# Custom site configuration
lang: en
